### ISSUE TITLE
h

### ISSUE THREAD

**Issue by esblygiad** [SneezingCactus/sneezingcactus.github.io#8]
Hi we are try to contact yuo abot you car extended warenty .Please acpept this mesage as us try to helep you you are. You. Please pay us Xfinty Amazo &YouTube gift giftcard. You have $9999999999999to pay Pay it now. Pay it. Now. Now pay.Ok.Ok.Ok K Ok. Plese pay me I am no moeny. Money. Ok I will hakc you if you not pay me. Prepeare to hacked....... `$ sudoe hakc %user &fart` you got haked. Haked!!!! iM You acont now. You. Im hack you twie!!!!!!!!<><> Okstop Pay me now.Or else. I hack youuo frotnite acount all v Buck get gone. STOP THE Madnes !! >:(Im anger you. F* Fyou. You. Hakcing you 3time. Carwaranty. Pay me or hacked!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Now.

**Comment by SneezingCactus** [comment]
NOOOOOOOOOOOOO i got haked :frowning:
